spring:
  application:
    name: MeetNow

  datasource:
    url:
    username: qwe
    password: qwe
    driver-class-name: org.postgresql.Driver

app:
  event-sorting:
    distance-control-points:
      - distance: 0.0
        value: 1.0
      - distance: 1.0
        value: 1.0
      - distance: 3.0
        value: 0.8
      - distance: 7.0
        value: 0.4
      - distance: 15.0
        value: 0.2
      - distance: 25.0
        value: 0.0
    decay-rate-for-history-interests: 0.05


